version: '3.8'

services:
  tiny-stack:
    image: tiny-stack
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4321:4321"
    volumes:
      - $PWD/data:/data